# Generated by Django 5.2.1 on 2025-07-12 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('ticket_id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('issue_type', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, max_length=10)),
                ('submitted_by', models.CharField(default='Patient', max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In_Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('on_hold', 'On_Hold')], db_index=True, default='open', max_length=15)),
                ('assigned_department', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_no', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=20)),
                ('Block', models.CharField(max_length=10)),
                ('Floor_no', models.IntegerField()),
                ('ward', models.CharField(max_length=20)),
                ('speciality', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('dataenc', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complaint_images/')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Issue_Category',
            fields=[
                ('issue_category_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('issue_category_name', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_categories', to='complaints.department')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='complaints.room'),
        ),
    ]
