# Generated by Django 5.2.1 on 2025-07-12 16:57

import django.db.models.deletion
from django.db import migrations, models


def set_assigned_department_null(apps, schema_editor):
    Complaint = apps.get_model('complaints', 'Complaint')
    # Set assigned_department to None for all existing Complaint objects
    # This is necessary because the field is changing from CharField to ForeignKey
    # and existing string values might not correspond to valid Department primary keys.
    Complaint.objects.all().update(assigned_department=None)


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_assigned_department_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='complaint',
            name='assigned_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_complaints', to='complaints.department'),
        ),
    ]