# Generated by Django 5.2.1 on 2025-09-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_assigned_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='issue_category',
            name='issue_category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
